services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "65000:65000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
